---
title: "Reproducible Research: Peer Assessment 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data

```{R}
setwd("C:/Users/Javier Ng/Desktop/Coursera/Coursera_Reproducible-Research/Week 2/Old")
df <- read.csv("activity.csv")
df$date <- as.Date(df$date, "%Y-%m-%d")
df <- as.data.frame(df)
```

## Histogram of the total number of steps taken each day

```{R}
library(ggplot2)
steps <- aggregate(df$steps, by = list(Date = df$date), FUN = sum) #total number of steps by day
colnames(steps) <- c("Date", "Total")
ggplot(na.omit(steps), aes(Date, Total)) + geom_bar(stat = 'identity') 
```

## What is mean total number of steps taken per day?

```{R}
mean(na.omit(steps$Total))
median(na.omit(steps$Total))
```


## What is the average daily activity pattern?

```{R}
five_min_steps <- aggregate(steps ~ interval, data = df, FUN =mean)
TimeSeries1 <- ggplot(data = five_min_steps, aes(x = interval, y = steps)) + 
  geom_line() +
  geom_rug(sides='b') +
  xlab("Minutes in a Day") + 
  ylab("Total Number of Steps") +
  ggtitle("Average Number of Steps Taken of the 5-Minute Interval") +
  theme_classic()
print(TimeSeries1)

five_min_steps[which(five_min_steps$steps == max(five_min_steps$steps)),] #finding max value
```

## Imputing missing values

```{R}
library(naniar)
vis_miss(df) #show missing values
library(dplyr)
replace_with_mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
meanday <- (df %>% group_by(interval) %>% mutate(steps = replace_with_mean(steps))) #replacing missing values with mean from 5 min interval
```

```{R}
new_dataset <- as.data.frame(meanday)
new_steps <- aggregate(new_dataset$steps, by = list(new_dataset$date), FUN = sum)

names(new_steps)[names(new_steps) == "x"] <- "Total"
names(new_steps)[names(new_steps) == "Group.1"] <- "Date"

Timeseries2 <- ggplot(data = new_steps, aes(Total)) + 
  geom_histogram(binwidth = 1500, colour = "white") +
  xlab("Total Number of Steps Taken Each Day") +
  ylab("Count") +
  ggtitle("Histogram of the Total Number of Steps Taken Each Day with New Version Dataset")
print(Timeseries2)
```

Comparison between the two plots, new data and old data before imputation

```{R}
library(gridExtra)
grid.arrange(TimeSeries1, Timeseries2, ncol = 2)
```

From the comparison, we can see that the highest count of the new version data is larger than the one we have with NAs. The means of each dataset are same. The medians of each dataset are slightly different.

## Are there differences in activity patterns between weekdays and weekends?

Identifying weekday/weekend in the dates

```{R}
new_dataset$WeekendOrWeekday <- ifelse(weekdays(as.Date(new_dataset$date)) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), "Weekday", "Weekend")
head(new_dataset)
```

Plot to show the number of steps' differences between weekday or weekend, based on mean
  
```{R}
new_dataset <- (new_dataset %>% group_by(interval, WeekendOrWeekday) %>% summarise(Mean = mean(steps)))
ggplot(new_dataset, mapping = aes(x = interval, y = Mean)) + geom_line() +
    facet_grid(WeekendOrWeekday ~.) + xlab("Interval") + ylab("Mean of Steps") +
    ggtitle("Comparison of Average Number of Steps in Each Interval")
```

Observations: 

* People tend to wake up later during the weekends and stay up later
* Activity during the weekends are higher as most people are not confined by their working hours